"""Add field_2 to users

Revision ID: 2c350573e038
Revises: 260b88fb5b7e
Create Date: 2023-08-24 10:55:35.986032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c350573e038'
down_revision: Union[str, None] = '260b88fb5b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('field_2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'field_2')
    # ### end Alembic commands ###
